version: "3.3"

services:

  mysql:
    image: mysql:8.0.15
    container_name: app_db_mysql
    working_dir: /application/
    volumes:
      - ./db_files:/var/lib/mysql/
    command:
      - "--default-authentication-plugin=mysql_native_password"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=8888
      - MYSQL_DATABASE=db_app
      - MYSQL_USER=user
      - MYSQL_PASSWORD=8888
    ports:
      - "33063:3306"
    networks:
      - net


networks:
    net:
